import { SynthesisResponse } from "@/api/client";

/**
 * Transforms the synthesis response into Presenton Markdown slides.
 * Reorganizes content for executives first, then detailed appendices.
 */
export function transformToMarkdown(query: string, synthesis: SynthesisResponse): string[] {
    const slides: string[] = [];

    // 1. Title Slide
    slides.push(`
# Executive Strategy Report
## ${query}

Generated by layman.vuishere.com
`);

    // 2. Executive Summary (High-level insights, key takeaways, decision points)
    slides.push(`
# Executive Summary
**High-level Insights & Key Takeaways:**

${synthesis.summary}
`);

    // 3. Data Visualization (Decision Points) using Chart.js via QuickChart
    // Chart generation: Pareto frontier showing trade-offs
    const chartData = synthesis.pareto_data.map(d => ({ x: d.x, y: d.y, r: 8 }));
    
    // QuickChart JSON configuration
    const chartConfig = {
        type: 'bubble',
        data: {
            datasets: [{
                label: 'Models Trade-offs (Ease vs Capability)',
                data: chartData,
                backgroundColor: 'rgba(16, 185, 129, 0.5)',
                borderColor: '#10B981',
                borderWidth: 1
            }]
        },
        options: {
            plugins: {
                datalabels: {
                    display: true,
                    align: 'bottom',
                    backgroundColor: '#ccc',
                    borderRadius: 3,
                    font: { size: 10 }
                }
            },
            scales: {
                x: { title: { display: true, text: 'Ease of Use / Cost Efficiency' }, min: 0, max: 100 },
                y: { title: { display: true, text: 'Capability Score' }, min: 0, max: 100 }
            }
        }
    };
    
    // Attach labels to the points (workaround for bubble chart labels)
    // QuickChart URL encoding
    const encodedChart = encodeURIComponent(JSON.stringify(chartConfig));
    const chartUrl = `https://quickchart.io/chart?c=${encodedChart}&w=800&h=400&bkg=white`;

    slides.push(`
# Decision Framework: Pareto Analysis

![Pareto Frontier](${chartUrl})
`);

    // 4. Strategic Recommendations (Ranked Models)
    const topModel = synthesis.ranked_models[0];
    let rankedContent = `# Strategic Recommendations\n\n**Top Recommendation:** ${topModel.model_name}\n\n`;
    synthesis.ranked_models.forEach((m, i) => {
        rankedContent += `### #${i + 1} ${m.model_name}\n`;
        rankedContent += `- **Capabilities:** ${m.capabilities_score}/100 | **Ease:** ${m.ease_of_use_score}/100 | **Cost Efficiency:** ${m.cost_efficiency_score}/100\n`;
        rankedContent += `- ${m.rationale}\n\n`;
    });
    slides.push(rankedContent.trim());

    // 5. Implementation Roadmap
    let timelineContent = `# Implementation Roadmap\n\n`;
    synthesis.implementation_timeline.forEach(event => {
        timelineContent += `**${event.date}: ${event.title}**\n\n`;
        timelineContent += `- ${event.description}\n\n`;
    });
    slides.push(timelineContent.trim());

    // 6. Appendices: Deep Dive Research
    if (synthesis.appendix) {
        // Split appendix into multiple slides based on headers to avoid text overflow
        const appendixSections = synthesis.appendix.split(/(?=### )/g);
        
        appendixSections.forEach((section, index) => {
            if (section.trim()) {
                const titleModifier = index > 0 ? `(Part ${index + 1})` : '';
                slides.push(`
# Appendix: Deep Dive Research ${titleModifier}

${section.trim()}
`);
            }
        });
    }

    return slides;
}
