"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { fetchProfile, resetProfile } from "@/api/client";
import { UserCircle, Trash2, ShieldAlert } from "lucide-react";

export default function ProfileDashboard() {
  const queryClient = useQueryClient();
  const { data: profile, isLoading } = useQuery({
    queryKey: ["user-profile"],
    queryFn: fetchProfile,
  });

  const resetMutation = useMutation({
    mutationFn: resetProfile,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["user-profile"] });
    },
  });

  if (isLoading) return null;
  if (!profile || !profile.metadata || Object.keys(profile.metadata).length === 0) return null;

  const traits = profile.metadata.traits || {};

  return (
    <div className="max-w-4xl mx-auto mt-12 p-6">
      <div className="flex items-center justify-between mb-8 pb-6 border-b border-neutral-800/50">
          <div className="flex items-center gap-4">
              <div className="p-3 bg-blue-500/10 rounded-xl text-blue-400">
                  <UserCircle size={32} />
              </div>
              <div>
                  <h2 className="text-2xl font-bold text-white">Your Technical Persona</h2>
                  <p className="text-neutral-400 text-sm mt-1">LLM expansions will be tuned to these preferences.</p>
              </div>
          </div>
          <button 
             disabled={resetMutation.isPending}
             onClick={() => resetMutation.mutate()}
             className="flex items-center gap-2 px-4 py-2 rounded-lg bg-red-500/10 text-red-400 hover:bg-red-500/20 hover:text-red-300 transition-colors text-sm font-medium border border-red-500/20"
          >
              <Trash2 size={16} /> 
              {resetMutation.isPending ? "Resetting..." : "Reset Profile"}
          </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {Object.entries(traits).map(([category, value]) => (
              <div key={category} className="bg-neutral-900/40 border border-neutral-800 rounded-xl p-5 hover:border-neutral-700 transition-colors">
                  <div className="text-xs uppercase tracking-wider text-neutral-500 font-semibold mb-2">{category}</div>
                  <div className="text-lg text-white font-medium">{value as string}</div>
              </div>
          ))}
      </div>

      <div className="bg-blue-500/5 border border-blue-500/10 rounded-2xl p-6">
          <h3 className="font-semibold text-blue-300 mb-2 flex items-center gap-2">
            <ShieldAlert size={18} />
            Summary Generated by AI
          </h3>
          <p className="text-neutral-400 leading-relaxed text-sm">
             {profile.body}
          </p>
      </div>
    </div>
  );
}
